// Map DESIGN.md design tokens to a Tailwind theme fragment. Pure: no I/O.
//
// This bridges the visual layer (DESIGN.md tokens) into Tailwind so the two don't drift.
// `cambia tailwind` generates the fragment; `cambia tailwind --check` re-generates and
// diffs it against a committed file to catch drift in CI.

export type FontSizeValue = string | [string, Record<string, string>];

export interface TailwindThemeExtend {
  colors?: Record<string, string>;
  spacing?: Record<string, string>;
  borderRadius?: Record<string, string>;
  fontSize?: Record<string, FontSizeValue>;
  fontFamily?: Record<string, string[]>;
}

export interface TailwindTheme {
  extend: TailwindThemeExtend;
}

export type TailwindFormat = 'esm' | 'cjs' | 'json';

function stringMap(obj: Record<string, unknown>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v != null && typeof v !== 'object') out[k] = String(v);
  }
  return out;
}

/** Build a Tailwind `theme` fragment from a DESIGN.md front-matter object. */
export function tokensToTailwind(frontMatter: Record<string, any> | null): TailwindTheme {
  const fm = frontMatter || {};
  const extend: TailwindThemeExtend = {};

  if (fm.colors && typeof fm.colors === 'object') extend.colors = stringMap(fm.colors);
  if (fm.spacing && typeof fm.spacing === 'object') extend.spacing = stringMap(fm.spacing);
  // DESIGN.md `rounded` → Tailwind `borderRadius`.
  if (fm.rounded && typeof fm.rounded === 'object') extend.borderRadius = stringMap(fm.rounded);

  if (fm.typography && typeof fm.typography === 'object') {
    const fontSize: Record<string, FontSizeValue> = {};
    const fontFamily: Record<string, string[]> = {};
    for (const [name, t] of Object.entries<any>(fm.typography)) {
      if (!t || typeof t !== 'object') continue;
      if (t.fontSize != null) {
        const opts: Record<string, string> = {};
        if (t.lineHeight != null) opts.lineHeight = String(t.lineHeight);
        if (t.fontWeight != null) opts.fontWeight = String(t.fontWeight);
        fontSize[name] = Object.keys(opts).length ? [String(t.fontSize), opts] : String(t.fontSize);
      }
      if (t.fontFamily != null) fontFamily[name] = [String(t.fontFamily)];
    }
    if (Object.keys(fontSize).length) extend.fontSize = fontSize;
    if (Object.keys(fontFamily).length) extend.fontFamily = fontFamily;
  }

  return { extend };
}

/** True when the theme fragment carries no tokens at all. */
export function isEmptyTheme(theme: TailwindTheme): boolean {
  return Object.keys(theme.extend).length === 0;
}

/** Render the theme fragment as a deterministic file string (stable for drift checks). */
export function renderTailwindTheme(theme: TailwindTheme, format: TailwindFormat = 'esm'): string {
  const json = JSON.stringify(theme, null, 2);
  if (format === 'json') return `${json}\n`;
  const header = '// Generated by `cambia tailwind` from DESIGN.md. Do not edit by hand.\n';
  if (format === 'cjs') return `${header}module.exports = ${json};\n`;
  return `${header}export const cambiaTheme = ${json};\nexport default cambiaTheme;\n`;
}
